# Generated by Django 3.0.6 on 2020-06-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('contact', models.EmailField(max_length=30)),
                ('number', models.PositiveIntegerField(max_length=10)),
            ],
        ),
    ]
