# Generated by Django 3.0.6 on 2020-06-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='superiority',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
