# Generated by Django 3.0.6 on 2020-06-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200616_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
