# Generated by Django 3.0.6 on 2020-06-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200616_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rovers',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='rovers',
            name='image2',
            field=models.ImageField(null=True, upload_to='rov'),
        ),
        migrations.AddField(
            model_name='rovers',
            name='image3',
            field=models.ImageField(null=True, upload_to='rov'),
        ),
    ]
